# Generated by Django 2.2 on 2020-06-07 06:47

from django.db import migrations, models
import incident.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location1', models.CharField(choices=[('CH', 'Corporate Headoffice'), ('OPD', 'Operations Department'), ('WS', 'Work Station'), ('MD', 'Marketing Division')], default=incident.models.location('Corporate Headoffice'), max_length=10)),
                ('location2', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Fatal', 'Fatal')], default=incident.models.severity('Mild'), max_length=10)),
                ('cause', models.TextField()),
                ('actions', models.TextField()),
                ('type_env', models.BooleanField(default=False)),
                ('type_inju', models.BooleanField(default=False)),
                ('type_property', models.BooleanField(default=False)),
                ('type_vehicle', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(on_delete=None, to='person.person')),
            ],
        ),
    ]
