# Generated by Django 2.2 on 2020-06-07 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='actions',
            field=models.TextField(default='abcd'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='cause',
            field=models.TextField(default='abcd'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(default='efgh'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location2',
            field=models.TextField(default='abcd'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
